[phases.setup]
nixPkgs = ["python311", "nodejs_20", "postgresql_16"]

[phases.install]
cmds = [
    "cd backend && python -m pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python main.py"